/* An empty pie chart. */

let emptyChart = function() {
    c3.generate({
        data: {
            columns: [
                ["empty", 1],
            ],
            type : 'pie',
            colors: {
                "empty": "#808080"
            }
        }
    })
}

/* A dynamic pie chart generated by the user. */

let generateChart = function(user) {

    // Generate data.
    let columns = []
    for (let coin in user.coins) {
        let quantity = user.coins[coin]
        let value = coinStats[coin].price_usd
        let symbol = coinStats[coin].symbol
        let column = [symbol, quantity * value]
        columns.push(column)
    }

    c3.generate({
        bindto: '#chart',
        data: {
            columns: columns,
            type: "pie"
        },
    });
}
